name: Build and Run

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Run tests and collect coverage
      run: dotnet test Sender\BatteryDataStream.Test\BatteryDataStream.Test.csproj --collect:"XPlat Code Coverage"
	- name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Receiver for prod
      run: javac receiver/BmsReceiver.java
    - name: run
      run: dotnet run --project Sender\Sender\Sender.csproj | java -ea -classpath . src.main.java.batterystreamreceiver.ReceiverServiceImpl.java
	 